/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LimitConstraintView.java
 *
 * Created on Feb 28, 2010, 7:13:27 PM
 */
package gui.timetable.constraints.limit;

import business.timetable.Entity;
import business.timetable.constraints.ConstraintType;
import business.timetable.constraints.TimeSlotType;
import com.timetable.BasicException;
import com.timetable.gui.JMessageDialog;
import com.timetable.gui.MessageInf;
import gui.timetable.AppView;
import gui.timetable.constraints.Constraint;
import gui.timetable.constraints.ConstraintView;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Usman Aftab (08-0964)
 */
public class LimitConstraintView extends ConstraintView {

    /** Creates new form LimitConstraintView */
    public LimitConstraintView(Constraint constraint) {
        super(constraint);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entityComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        minLimitTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timeSlotTypeComboBox = new javax.swing.JComboBox();
        maxLimitTextBox = new javax.swing.JTextField();

        jLabel1.setLabelFor(entityComboBox);
        jLabel1.setText("Entity *");

        entityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        entityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setLabelFor(minLimitTextBox);
        jLabel3.setText("Min Limit");

        minLimitTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minLimitTextBoxKeyTyped(evt);
            }
        });

        jLabel2.setLabelFor(maxLimitTextBox);
        jLabel2.setText("Max Limit");

        jLabel4.setLabelFor(timeSlotTypeComboBox);
        jLabel4.setText("Timeslot type *");

        timeSlotTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        timeSlotTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotTypeComboBoxActionPerformed(evt);
            }
        });

        maxLimitTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxLimitTextBoxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minLimitTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxLimitTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(timeSlotTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(entityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSlotTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(minLimitTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(maxLimitTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void init(AppView appView) {
        super.init(appView);
        
        try {
            ArrayList<Entity> entities = Entity.getConstraintEntities(getAppView().getSession(), ConstraintType.Limit);
            DefaultComboBoxModel model = new DefaultComboBoxModel(entities.toArray());
            entityComboBox.setModel(model);

            ArrayList<TimeSlotType> timeSlotTypes = TimeSlotType.getConstraintTimeSlotTypes(getAppView().getSession(), ConstraintType.Limit);
            model = new DefaultComboBoxModel(timeSlotTypes.toArray());
            timeSlotTypeComboBox.setModel(model);
        } catch (BasicException ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER, ex.getMessage(), ex));
        }
    }

    @Override
    public void enableComponents(boolean b) {
        entityComboBox.setEnabled(b);
        minLimitTextBox.setEnabled(b);
        maxLimitTextBox.setEnabled(b);
        timeSlotTypeComboBox.setEnabled(b);
    }

    @Override
    public void changeSelection(business.timetable.constraints.Constraint constraint) {
        setChanging(true);
        business.timetable.constraints.limit.LimitConstraint limitConstraint =
                (business.timetable.constraints.limit.LimitConstraint) constraint;

        entityComboBox.setSelectedItem(limitConstraint.getEntity());
        minLimitTextBox.setText(String.valueOf(limitConstraint.getMinLimit()));
        maxLimitTextBox.setText(String.valueOf(limitConstraint.getMaxLimit()));
        timeSlotTypeComboBox.setSelectedItem(limitConstraint.getTimeSlotType());
        setChanging(false);
    }

    public Entity getEntity() {
        return (Entity) entityComboBox.getSelectedItem();
    }

    public int getMaxLimit() {
        return Integer.parseInt(maxLimitTextBox.getText());
    }

    public int getMinLimit() {
        return Integer.parseInt(minLimitTextBox.getText());
    }

    public TimeSlotType getTimeSlotType() {
        return (TimeSlotType) timeSlotTypeComboBox.getSelectedItem();
    }

    private void entityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityComboBoxActionPerformed
        setDirty(true);
    }//GEN-LAST:event_entityComboBoxActionPerformed

    private void timeSlotTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotTypeComboBoxActionPerformed
        setDirty(true);
    }//GEN-LAST:event_timeSlotTypeComboBoxActionPerformed

    private void minLimitTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minLimitTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_minLimitTextBoxKeyTyped

    private void maxLimitTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxLimitTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_maxLimitTextBoxKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox entityComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField maxLimitTextBox;
    private javax.swing.JTextField minLimitTextBox;
    private javax.swing.JComboBox timeSlotTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
