/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GapConstraintView.java
 *
 * Created on Feb 28, 2010, 7:12:17 PM
 */
package gui.timetable.constraints.gap;

import business.timetable.Entity;
import business.timetable.constraints.ConstraintType;
import business.timetable.constraints.TimeSlotType;
import com.timetable.BasicException;
import com.timetable.gui.JMessageDialog;
import com.timetable.gui.MessageInf;
import gui.timetable.AppView;
import gui.timetable.constraints.Constraint;
import gui.timetable.constraints.ConstraintView;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;

/**
 *
 * @author Usman Aftab (08-0964)
 */
public class GapConstraintView extends ConstraintView {

    /** Creates new form GapConstraintView */
    public GapConstraintView(Constraint constraint) {
        super(constraint);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timeSlotTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        minGapTextBox = new javax.swing.JTextField();
        maxGapTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maxSucTextBox = new javax.swing.JTextField();
        minSucTextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        entityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        entityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Entity *");

        jLabel4.setText("Timeslot type *");

        timeSlotTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        timeSlotTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Min Gap");

        minGapTextBox.setName("minGapTextBox"); // NOI18N
        minGapTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minGapTextBoxKeyTyped(evt);
            }
        });

        maxGapTextBox.setName("maxGapTextBox"); // NOI18N
        maxGapTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxGapTextBoxKeyTyped(evt);
            }
        });

        jLabel2.setText("Max Gap");

        maxSucTextBox.setName("maxSucTextBox"); // NOI18N
        maxSucTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxSucTextBoxKeyTyped(evt);
            }
        });

        minSucTextBox.setName("minSucTextBox"); // NOI18N
        minSucTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minSucTextBoxKeyTyped(evt);
            }
        });

        jLabel6.setText("Min Succession");

        jLabel7.setText("Max Succession");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(entityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeSlotTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minSucTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minGapTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxSucTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxGapTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSlotTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(minGapTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(maxGapTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(minSucTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(maxSucTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void init(AppView appView) {
        super.init(appView);
        
        try {
            ArrayList<Entity> entities = Entity.getConstraintEntities(getAppView().getSession(), ConstraintType.Gap);
            DefaultComboBoxModel model = new DefaultComboBoxModel(entities.toArray());
            entityComboBox.setModel(model);

            ArrayList<TimeSlotType> timeSlotTypes = TimeSlotType.getConstraintTimeSlotTypes(getAppView().getSession(), ConstraintType.Gap);
            model = new DefaultComboBoxModel(timeSlotTypes.toArray());
            timeSlotTypeComboBox.setModel(model);
        } catch (BasicException ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER, ex.getMessage(), ex));
        }
    }

    @Override
    public void enableComponents(boolean b) {
        entityComboBox.setEnabled(b);
        timeSlotTypeComboBox.setEnabled(b);
        minGapTextBox.setEnabled(b);
        maxGapTextBox.setEnabled(b);
        minSucTextBox.setEnabled(b);
        maxSucTextBox.setEnabled(b);
    }

    @Override
    public void changeSelection(business.timetable.constraints.Constraint constraint) {
        setChanging(true);
        business.timetable.constraints.gap.GapConstraint gapConstraint =
                (business.timetable.constraints.gap.GapConstraint) constraint;

        entityComboBox.setSelectedItem(gapConstraint.getEntity());
        minGapTextBox.setText(String.valueOf(gapConstraint.getMinGap()));
        maxGapTextBox.setText(String.valueOf(gapConstraint.getMaxGap()));
        minSucTextBox.setText(String.valueOf(gapConstraint.getMinSuccession()));
        maxSucTextBox.setText(String.valueOf(gapConstraint.getMaxSuccession()));
        timeSlotTypeComboBox.setSelectedItem(gapConstraint.getTimeSlotType());
        setChanging(false);
    }

    public Entity getEntity() {
        return (Entity) entityComboBox.getSelectedItem();
    }

    private int getValueInInt(JTextField textBox) {
        return Integer.parseInt(textBox.getText());
    }

    public int getMinGap() {
        return getValueInInt(minGapTextBox);
    }

    public int getMaxGap() {
        return getValueInInt(maxGapTextBox);
    }

    public int getMinSuccession() {
        return getValueInInt(minSucTextBox);
    }

    public int getMaxSuccession() {
        return getValueInInt(maxSucTextBox);
    }

    public TimeSlotType getTimeSlotType() {
        return (TimeSlotType) timeSlotTypeComboBox.getSelectedItem();
    }

    private void entityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityComboBoxActionPerformed
        setDirty(true);
}//GEN-LAST:event_entityComboBoxActionPerformed

    private void timeSlotTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotTypeComboBoxActionPerformed
        setDirty(true);
}//GEN-LAST:event_timeSlotTypeComboBoxActionPerformed

    private void minGapTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minGapTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_minGapTextBoxKeyTyped

    private void maxGapTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxGapTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_maxGapTextBoxKeyTyped

    private void minSucTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minSucTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_minSucTextBoxKeyTyped

    private void maxSucTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxSucTextBoxKeyTyped
        setDirty(true);
    }//GEN-LAST:event_maxSucTextBoxKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox entityComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField maxGapTextBox;
    private javax.swing.JTextField maxSucTextBox;
    private javax.swing.JTextField minGapTextBox;
    private javax.swing.JTextField minSucTextBox;
    private javax.swing.JComboBox timeSlotTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
