/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomizeTT.java
 *
 * Created on Jun 26, 2010, 3:24:26 PM
 */
package gui.timetable.customize;

import business.timetable.classrooms.ClassRoom;
import business.timetable.courses.Course;
import business.timetable.department.Department;
import business.timetable.department.Departments;
import business.timetable.representation.RepresentationRow;
import business.timetable.representation.RepresentationRows;
import business.timetable.semester.Semester;
import business.timetable.teachers.Teacher;
import business.timetable.timeslots.TimeSlot;
import com.timetable.BasicException;
import com.timetable.gui.JMessageDialog;
import com.timetable.gui.MessageInf;
import gui.timetable.*;
import gui.timetable.common.FilterChangedEvent;
import gui.timetable.common.FilterChangedListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;

/**
 *
 * @author Usman Aftab (08-0964)
 */
public class CustomizeTT extends javax.swing.JPanel implements AppPanel {

    private AppView appView;
    private RepresentationRows representationRows;

    /** Creates new form CustomizeTT */
    public CustomizeTT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityFilter = new gui.timetable.common.EntityFilter();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        automated = new gui.timetable.customize.Automated();
        manual = new gui.timetable.customize.Manual();

        setName("Customize Time Table"); // NOI18N

        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jLabel1.setText("Current Allocation");

        jTabbedPane1.addTab("Automated", automated);
        jTabbedPane1.addTab("Manual", manual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entityFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                        .addGap(104, 104, 104)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entityFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void init(AppView appView) {
        this.appView = appView;
        entityFilter.init(appView);
        entityFilter.addFilterChangedListerner(new FilterChangedListener() {

            public void filterSemesterChanged(FilterChangedEvent evt) {
                entityFilterDepartmentChanged(evt);
            }

            public void filterDepartmentChanged(FilterChangedEvent evt) {
                entityFilterSemesterChanged(evt);
            }
        });

        for (JCheckBox checkBox : entityFilter.getCheckBoxs()) {
            checkBox.setSelected(true);
        }

        automated.init(appView);
        manual.init(appView);
        entityFilterSemesterChanged(null);
    }

    public AppView getAppView() {
        return appView;
    }

    private void entityFilterDepartmentChanged(FilterChangedEvent evt) {
        setList(representationRows.findBy(entityFilter.getSemester(), entityFilter.getDepartments()).getAllValues());
    }

    private void entityFilterSemesterChanged(FilterChangedEvent evt) {
        try {
            setList();
        } catch (Exception ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER, ex.getMessage(), ex));
        }
    }

    private void setList() throws BasicException {
        Semester semester = entityFilter.getSemester();
        Departments departments = Departments.getData(appView.getSession());
        representationRows = RepresentationRows.getData(appView.getSession(), departments, semester);
        setList(representationRows.findBy(semester, entityFilter.getDepartments()).getAllValues());
    }

    private void setList(ArrayList<RepresentationRow> list) {
        DefaultListModel defaultListModel = new DefaultListModel();
        for (RepresentationRow representationRow : list) {
            defaultListModel.addElement(representationRow);
        }
        jList.setModel(defaultListModel);
    }

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        RepresentationRow representationRow = (RepresentationRow) jList.getSelectedValue();
        ClassRoom classRoom = representationRow.getClassRoom();
        TimeSlot timeSlot = representationRow.getTimeSlot();
        Course course = representationRow.getCourse();
        Teacher teacher = representationRow.getTeacher();
        Department department = representationRow.getDepartment();
        Semester semester = representationRow.getSemester();
        automated.changeSelection(classRoom, timeSlot, course, teacher, semester, department);
        manual.changeSelection(classRoom, timeSlot, course, teacher, semester, department);
    }//GEN-LAST:event_jListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.timetable.customize.Automated automated;
    private gui.timetable.common.EntityFilter entityFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.timetable.customize.Manual manual;
    // End of variables declaration//GEN-END:variables
}
